### ISSUE TITLE
Question on feature overlap with @excid3/tailwindcss-stimulus-components

### ISSUE THREAD

**Issue by swistaczek** [getrailsui/railsui-stimulus#1]
Hey @justalever, thanks for kicking off this library and for your effort to make product development easier with RailsUI!

When I reviewed your project, I thought it was pretty similar to and overlapped with the [@excid3](https://github.com/excid3) project: https://github.com/excid3/tailwindcss-stimulus-components. I'd like to know how your approach differs or if you would like to collaborate on one shared, more significant project with excid3 and the community.

✌️

**Comment by justalever** [comment]
Hey @swistaczek, Thanks for the issue! I will keep this in mind in the future. For now, I'm pushing out more components that might not align with Chris's approach. I am certainly open to merging projects at some point.
